language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

python:
    - 2.7
    - 3.5

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - SETUP_CMD='test'
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES=''
        - PIP_DEPENDENCIES='git+https://github.com/spacetelescope/pyasdf.git#egg=pyasdf'
    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test'

matrix:
    include:

        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Dev astropy
        - python: 2.7
          env: ASTROPY_VERSION=development
        - python: 3.5
          env: ASTROPY_VERSION=development

        # Numpy
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 3.5
          env: NUMPY_VERSION=1.9
        - python: 3.5
          env: NUMPY_VERSION=1.10

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - python setup.py $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    # - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='packagename/tests/coveragerc'; fi
